# Generated by Django 4.1.7 on 2023-08-23 22:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('address_street', models.TextField()),
                ('address_city', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('local_church_name', models.CharField(max_length=255)),
                ('local_church_branch', models.CharField(max_length=255)),
                ('church_address_street', models.TextField()),
                ('church_address_city', models.CharField(max_length=255)),
                ('church_address_state', models.CharField(max_length=255)),
                ('pastors_name', models.CharField(max_length=255)),
                ('time_in_church', models.CharField(max_length=255)),
                ('active_in_church', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('consistency', models.BooleanField()),
                ('detailed_consistency', models.TextField()),
                ('explained_interest', models.TextField()),
                ('Emergency_contact_name', models.CharField(max_length=255)),
                ('Emergency_contact_relationship', models.CharField(max_length=255)),
                ('Emergency_contact_phone_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
