# Generated by Django 4.1.7 on 2023-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Emergency_contact_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='active_in_church',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='church_address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='church_address_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='church_address_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='consistency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='department',
            field=models.CharField(blank=True, choices=[('MEDIA', 'MEDIA'), ('WORSHIP', 'WORSHIP'), ('USHERING', 'USHERING'), ('TRANSPORT_&_LOGISTICS', 'TRANSPORT_&_LOGISTICS'), ('TECHNICAL', 'TECHNICAL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='detailed_consistency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='explained_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='local_church_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='local_church_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='pastors_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='time_in_church',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
